name: Run paho tests

on: 
  pull_request:
  push:
    tags:
      - v*
  repository_dispatch:
    types: [run_tests]

jobs:

    run_paho_tests:

        runs-on: ubuntu-latest

        steps:
        - name: Install docker-compose
          run: | 
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
        - uses: actions/checkout@v1
        - name: get deps
          run: |
            if [ ${{ github.event_name}} = 'repository_dispatch' ]; then version=${{ github.event.client_payload.version }}; else version=$(echo ${{ github.ref }} | sed -r  "s ^refs/heads/|^refs/tags/(.*) \1 g"); fi
            if [ ! -z $(echo $version | grep -oE "^[ev0-9]+\.[0-9]+(\.[0-9]+)?") ]; then deps_version=$version; else deps_version=""; fi

            echo "::set-env name=EMQX_DEPS_DEFAULT_VSN::$deps_version"
            echo "::set-env name=version::$version"

            docker run -i --rm \
              -e GITHUB_RUN_ID=$GITHUB_RUN_ID \
              -e GITHUB_REF=$GITHUB_REF \
              -e EMQX_DEPS_DEFAULT_VSN=$deps_version \
              -v $(pwd):/emqx-rel \
              emqx/build-env:erl22.3-debian10 \
              bash -c "make -C /emqx-rel deps-emqx"
        - name: make emqx image
          run: TARGET=emqx/emqx make docker
        - name: make paho tests
          run: TARGET=emqx/emqx PAHO_BRANCH="develop-4.0" make -C .ci/paho_tests test
