name: Run all test cases

on: 
  repository_dispatch:
  push:
    branch:
      - develop
      - master
      - release-*
    tags:
      - v*
# on: [push]

jobs:

    run_test_case:

        runs-on: ubuntu-latest

        steps:
        - name: Install docker-compose
          run: | 
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
        - uses: actions/checkout@v2
          with:
            repository: emqx/emqx-integration-test
            token: ${{ secrets.AccessToken }} 
            path: emqx-integration-test
        - name: Run all test cases
          run: |
            cd emqx-integration-test/docker-compose
            sudo docker-compose -p emqx_auto_func_test up -d --build
            sudo docker ps -a
            sudo docker exec emqx_auto_func_test_emqx_1 bash -xc "cd /tests; sed -i '/^set.*/d' run_emqx.sh; export EMQX_DEPS_DEFAULT_VSN=$(echo ${{ github.ref }} | gsed -r  "s .*/.*/(.*) \1 g"); ./run_emqx.sh emqx-ce.spec "
            sudo docker exec emqx_auto_func_test_python_1 bash -xc "cd /tests && python ./boot.py "
            sudo docker-compose -p emqx_auto_func_test down
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: emqx-integration-test/docker-compose/files/logs
        - name: Run paho test
          run: |
            cd emqx-integration-test/paho-test
            EMQX_DEPS_DEFAULT_VSN=develop TARGET=emqx/emqx PAHO_BRANCH="develop-4.0" make 